woopstar/hsem

custom_components/hsem/utils/misc.py

added few other sensors states and boolean value for them

fix: Unexpected sensor states

---

custom_components/hsem/config_flow.py
custom_components/hsem/const.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/sensor.py
custom_components/hsem/translations/en.json

fix: add ev sensors to config flow

---

custom_components/hsem/config_flow.py
custom_components/hsem/const.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/sensor.py
custom_components/hsem/translations/en.json
custom_components/hsem/utils/recommendations.py

This will add hsem_huawei_solar_batteries_grid_charge_cutoff_soc for config flow and also add a new function to calculate the best time to charge the battery.

fix: add charge at best time for battery

---

custom_components/hsem/const.py
custom_components/hsem/custom_sensors/house_consumption_energy_average_sensor.py
custom_components/hsem/custom_sensors/house_consumption_energy_sensor.py
custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/utils/ha.py

It will clean up the code and introduce a new utils function to grab state from entities and convert it to the needed type. This will reduce repeated code.
Adds device class to energy sensors.
It will also regularly update power and energy sensors, not just when the input sensor updates.
Reduce the output logging again after introducing the battery charging feature in v0.2.5
Do not restore the old state of the working mode sensor, as it will be calculated anyway.

fix: minor cleanup fixes

---

custom_components/hsem/custom_sensors/ha_sensor_integral.py

Make sure we use the power sensor as source for our integral sensor.

fix: use power sensor as source

---

README.md
custom_components/hsem/config_flow.py
custom_components/hsem/const.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/translations/en.json

fix: Allow adjustments of charging time for batteries

---

custom_components/hsem/const.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/utils/misc.py
custom_components/hsem/utils/recommendations.py
custom_components/hsem/utils/sensornames.py

fix: add energy needs attributes and cleanup code

---

custom_components/hsem/config_flow.py

fix: allow switch and input booleans for ev charger status

---

custom_components/hsem/custom_sensors/working_mode_sensor.py

fix: only charge when SoC diff is above 5%

---

custom_components/hsem/config_flow.py

fix: fix config flow missing errors variable

---

README.md
custom_components/hsem/const.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/flows/huawei_solar.py

fix: add batteries rated capacity to setup/config flow

---

custom_components/hsem/flows/ev.py
custom_components/hsem/flows/huawei_solar.py

fix: entity is neither a valid entity ID nor a valid UUID

---

custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
custom_components/hsem/custom_sensors/integration_sensor.py
custom_components/hsem/custom_sensors/statistics_sensor.py
custom_components/hsem/custom_sensors/utility_meter_sensor.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/entity.py
custom_components/hsem/flows/huawei_solar.py
custom_components/hsem/translations/en.json

fix: fix sensors and config flow

---

custom_components/hsem/custom_sensors/avg_sensor.py

This will fix the energy sensors not having measurements, related to the discussion in #24 
See more at https://github.com/woopstar/hsem/issues/24#issuecomment-2676832606

fix: avg sensor measurements never being set

---

.devcontainer/README.md
.devcontainer/devcontainer.json
.github/workflows/tests.yml
.gitignore
scripts/develop
scripts/setup

Improve the development environment by updating Python versions in the CI configuration, enhancing the devcontainer setup, and adding useful development scripts. This streamlines the setup process for contributors.

chore: Update CI Python versions and enhance devcontainer setup

---

.gitignore
.tox/py310/.tox-info.json
.vscode/extensions.json
.vscode/settings.json
custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
custom_components/hsem/custom_sensors/working_mode_sensor.py

This pull request includes changes to improve project configuration, streamline exception handling in the codebase, and enhance the development environment. Below is a summary of the most important changes:
* [`.vscode/extensions.json`](diffhunk://#diff-c16655a98a3ee89a7636a59c59a72b0e93649e3a1e947327cfc43a1336b4e912R1-R31): Added a list of recommended VS Code extensions to improve the development workflow, including tools for Python formatting, YAML editing, GitHub integrations, and more.
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357R1-R44): Added specific editor settings for `home-assistant`, `python`, and `yaml` file types, enabling features like auto-formatting, organized imports, and YAML custom tags. Also included …

chore: update .gitignore, remove .tox configuration, and add VSCode settings and extensions

---

custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/utils/misc.py

feat: enhance working mode sensor logic and add utility for setting number values

---

custom_components/hsem/const.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/flows/energidataservice.py
custom_components/hsem/flows/ev.py
custom_components/hsem/translations/en.json

Introduce new configuration options for maximum discharge power and force maximum discharge power for the EV charger, along with updates to settings and translations.

feat: add configuration options for EV charger discharge power settings

---

custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/flows/batteries_schedule_1.py
custom_components/hsem/flows/batteries_schedule_2.py
custom_components/hsem/flows/batteries_schedule_3.py
custom_components/hsem/flows/energidataservice.py
custom_components/hsem/translations/en.json

bug: batteries should stop discharging when the hsem is operating in ev charging mode if the force max is disabled

---

custom_components/hsem/utils/misc.py

bug: fix missing indentation in state map check

---

custom_components/hsem/custom_sensors/working_mode_sensor.py

This will add support for the price sensor provided from Strømligning.
https://github.com/MTrab/stromligning
The integration does not expose an export sensor, but the import one is `sensor.stromligning_current_price_vat` or `Current incl. VAT`

enhancement: Add support for Strømligning price sensor

---

custom_components/hsem/config_flow.py
custom_components/hsem/const.py
custom_components/hsem/custom_sensors/working_mode_sensor.py
custom_components/hsem/flows/months.py
custom_components/hsem/options_flow.py
custom_components/hsem/translations/en.json

This PR will allow the user to set months considered as Winter/Spring in the config/options flow. Unchecked months will be considered as Summer/Autumn months.

enhancement: Add option to set winter/spring months in config flow
